// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package models

import (
	"database/sql"
)

type Player struct {
	Playerid  string
	Birthyear sql.NullInt32
	Namefirst sql.NullString
	Namelast  sql.NullString
}
